services:
  redis:
    image: redis:7-alpine
    container_name: hng14-stage2-devops-redis-1
    restart: unless-stopped
    networks:
      - hngjob
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "${REDIS_CPU_LIMIT:-0.25}"
          memory: "${REDIS_MEMORY_LIMIT:-256M}"

  api:
    build: ./api
    container_name: hng14-stage2-devops-api-1
    restart: unless-stopped
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hngjob
    ports:
      - "${API_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "${API_CPU_LIMIT:-0.5}"
          memory: "${API_MEMORY_LIMIT:-512M}"

  worker:
    build: ./worker
    container_name: hng14-stage2-devops-worker-1
    restart: unless-stopped
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hngjob
    deploy:
      resources:
        limits:
          cpus: "${WORKER_CPU_LIMIT:-0.5}"
          memory: "${WORKER_MEMORY_LIMIT:-512M}"

  frontend:
    build: ./frontend
    container_name: hng14-stage2-devops-frontend-1
    restart: unless-stopped
    environment:
      - API_URL=${API_URL:-http://api:8000}
      - PORT=${FRONTEND_PORT:-3000}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - hngjob
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "${FRONTEND_CPU_LIMIT:-0.5}"
          memory: "${FRONTEND_MEMORY_LIMIT:-256M}"

networks:
  hngjob:
    driver: bridge
